// mod abc_199_a;
// mod abc_197_a;
// mod abc_154_d;
// mod abc_167_c;
// mod caesar_enc;
// mod prime100;
// mod maze;
// mod bingo;
// mod http_client_get;
// mod http_client_post;
// mod http_client_get_async;
// mod http_client_tls_get;
// mod bmi;
// mod counter;
// mod tukimei;
// mod hashmap_check;
// mod hashmap_matcher;
// mod compairtext;
// mod jisho;
// mod fizz_buzz_file;
// mod fizz_buzz_file_2;
// mod rec_fib;
// mod findfile;
// mod cur_file;
// mod tuple_goods;
// mod tuple_goods_struct;
// mod array_init;
// mod array_init_2;
// mod array_get;
// mod slice_str;
mod slice_show;

fn main() {
    // abc_199_a::exec();
    // abc_197_a::exec();
    // abc_154_d::exec();
    // abc_167_c::exec();
    // caesar_enc::main();
    // prime100::main();
    // maze::main();
    // bingo::main();
    // _ = http_client_get::main();
    // _ = http_client_post::main();
    // _ = http_client_get_async::main();
    // _ = http_client_tls_get::main();
    // bmi::main();
    // counter::main();
    // tukimei::main();
    // hashmap_check::main();
    // hashmap_matcher::main()
    // compairtext::main();
    // jisho::main();
    // fizz_buzz_file::main();
    // fizz_buzz_file_2::main();
    // rec_fib::main();
    // findfile::main();
    // cur_file::main();
    // tuple_goods::main();
    // tuple_goods_struct::main();
    // array_init::main();
    // array_init_2::main();
    // array_get::main();
    // slice_str::main();
    slice_show::main();
}